
- name für das micro service framework
  * Kronos - Der vater von Zeus
  * Appollon - Ist der Gott der Poesie, der Heilung, des Frühlings und des Lichts.
- neuer name für donkey
  * Heimdall - ist in der nordischen Mythologie ein Gott aus dem Göttergeschlecht der Asen, der als Wächter der Götter dargestellt wird. Wird gereits für eine weit verbreitete Kerberos implementierung benutzt

  * Prokyon	 - Alpha Canis Minoris Der Name eines Sternes

- find better name for step implementation "type"
  * stepImplementationName
  * impl

  - rename stepImplementation.js -> stepImplementations.js
  - rename endpointImplementation.js -> endpointImplementations.js

- Die meta informationen aus einer Step implementaion sollen bei der Ausführung des Steps wieder abrufbar sein.
Nachfolgend ein Auszug aus einer implementierung.

[source,javascript]
----
exports.stepImplementations = {
	"file-write": {
		"description": "Opens a file for reading",
		"endpoints": {
			"in": {
				"direction": "in",
				"uti": "public.data",
				"contentInfo": {
					"fileName": {
						"description": "The file name of the file to write",
						"mandatory": false,
						"type": "string"
					}
				}
			},
		},
		"config": {
			"fileName": {
				"description": "The file name of the file to write",
				"mandatory": false,
				"type": "string"
			}
		},

		"initialize": function (manager, step) {
			// get the endpoint
			const in1 = step.endpoints.in.implementation();
			const in1ParamDef = step.endpoints.in.contentInfo; // step.meta.endpoints.in.info ??
			const stepParamDef = step.meta.config;
			const stepConfig = step.config;


			for (let request of in1) {
				// get the info parameter hash
				let info = request.info;

				// get the input stream
				let inStream = request.stream;

				// validate the configs
				const myConfig = validator(in1ParamDef, [stepConfig, info]);
				const fileName = myConfig.fileName;

				var destinationStream = fs.createWriteStream(fileName);

				inStream.pipe(destinationStream);
			}
		}
	}
};
----

* Alles was unter 'file-write' definiert ist sollte über 'step.metainfo' erreichbar sein.
über den Namen des keys können wir noch diskutieren.
