=== Service Manager

The service manager is the heart of the framework.

==== Register Step
This method registers a new step factory. This factory is used to create step instances while
creating a flow. Each step referenced from a flow needs first be registered at the service manager.

[source,js]
----
manager.registerStep(step);
----
Register a new step factory at the manager

If a new step was registered at the manager it will emit an event +
''stepRegistered, step''.

==== Register Flow
Register a new flow at the manager. If a flow was registered it could be used.


[source,js]
----
manager.registerFlow(flow);
----
Register a new flow at the manager

If a new flow was registered at the manager it will emit an event +
''flowRegistered, flow'' +
or +
''flowStateChanged, flow'' +
if there was an existing flow before.

==== Delete Flow
Deletes an existing flow from the manager. Before deletion it will be stopped if necessary.

[source,js]
----
manager.deleteFlow(flowName);
----
Deletes the flow with the given name
